
# keep as fallback
# java-jar schoolapp.jar --spring.profiles.active=prod
spring.profiles.active=dev
spring.application.name=edu-analysis-app
server.port=8080

security.bcrypt.strength=12

# for using Greek characters in the messages_el.properties file.
spring.messages.encoding=UTF-8

