-- V1__initial_schema.sql
-- PostgreSQL

-- =========================
-- Security / Auth tables
-- =========================
CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_roles      PRIMARY KEY (id),
    CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE INDEX idx_roles_name ON roles (name);

CREATE TABLE capabilities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255) NULL,
    CONSTRAINT pk_capabilities      PRIMARY KEY (id),
    CONSTRAINT uk_capabilities_name UNIQUE (name)
);

CREATE INDEX idx_capabilities_name ON capabilities (name);

CREATE TABLE roles_capabilities (
    role_id       BIGINT NOT NULL,
    capability_id BIGINT NOT NULL,
    CONSTRAINT pk_roles_capabilities PRIMARY KEY (role_id, capability_id),
    CONSTRAINT fk_roles_capabilities_role
        FOREIGN KEY (role_id) REFERENCES roles (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_roles_capabilities_capability
        FOREIGN KEY (capability_id) REFERENCES capabilities (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_roles_capabilities_capability_id ON roles_capabilities (capability_id);

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID         NOT NULL,
    username   VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role_id    BIGINT       NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ  NULL,
    CONSTRAINT pk_users          PRIMARY KEY (id),
    CONSTRAINT uk_users_uuid     UNIQUE (uuid),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id) REFERENCES roles (id)
        ON DELETE RESTRICT
);

CREATE INDEX ix_users_role_id   ON users (role_id);
CREATE INDEX ix_users_deleted    ON users (deleted);
CREATE INDEX ix_users_deleted_at ON users (deleted_at);


-- =========================
-- Domain tables
-- =========================
CREATE TABLE firms (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_firms      PRIMARY KEY (id),
    CONSTRAINT uk_firms_name UNIQUE (name)
);

CREATE INDEX idx_firms_name ON firms (name);

CREATE TABLE attachments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filename     VARCHAR(255)  NULL,
    saved_name   VARCHAR(255)  NOT NULL,
    file_path    VARCHAR(1024) NOT NULL,
    content_type VARCHAR(255)  NULL,
    extension    VARCHAR(50)   NULL,
    created_at   TIMESTAMPTZ   NOT NULL,
    updated_at   TIMESTAMPTZ   NOT NULL,
    deleted      BOOLEAN       NOT NULL DEFAULT FALSE,
    deleted_at   TIMESTAMPTZ   NULL,
    CONSTRAINT pk_attachments           PRIMARY KEY (id),
    CONSTRAINT uk_attachments_saved_name UNIQUE (saved_name)
);

CREATE INDEX idx_attachments_deleted    ON attachments (deleted);
CREATE INDEX idx_attachments_deleted_at ON attachments (deleted_at);

CREATE TABLE personal_information (
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identity_number              VARCHAR(255) NOT NULL,
    place_of_birth               VARCHAR(255) NOT NULL,
    municipality_of_registration VARCHAR(255) NOT NULL,
    identity_file_id             BIGINT       NULL,
    created_at                   TIMESTAMPTZ  NOT NULL,
    updated_at                   TIMESTAMPTZ  NOT NULL,
    deleted                      BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at                   TIMESTAMPTZ  NULL,
    CONSTRAINT pk_personal_information            PRIMARY KEY (id),
    CONSTRAINT uk_personal_information_identity   UNIQUE (identity_number),
    CONSTRAINT uk_personal_information_identity_file  UNIQUE (identity_file_id),
    CONSTRAINT fk_personal_information_attachments
        FOREIGN KEY (identity_file_id) REFERENCES attachments (id)
        ON DELETE SET NULL
);

CREATE INDEX idx_personal_information_deleted    ON personal_information (deleted);
CREATE INDEX idx_personal_information_deleted_at ON personal_information (deleted_at);

CREATE TABLE analysts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid             UUID         NOT NULL,
    firstname        VARCHAR(255) NOT NULL,
    lastname         VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    firm_id          BIGINT       NULL,
    user_id          BIGINT       NOT NULL,
    personal_info_id BIGINT       NULL,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL,
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at       TIMESTAMPTZ  NULL,
    CONSTRAINT pk_analysts                  PRIMARY KEY (id),
    CONSTRAINT uk_analysts_uuid             UNIQUE (uuid),
    CONSTRAINT uk_analysts_email            UNIQUE (email),
    CONSTRAINT uk_analysts_user_id          UNIQUE (user_id),
    CONSTRAINT uk_analysts_personal_info_id UNIQUE (personal_info_id),
    CONSTRAINT fk_analysts_firms
        FOREIGN KEY (firm_id) REFERENCES firms (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_analysts_users
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_analysts_personal_information
        FOREIGN KEY (personal_info_id) REFERENCES personal_information (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_analysts_firm_id         ON analysts (firm_id);
CREATE INDEX idx_analysts_lastname        ON analysts (lastname);
CREATE INDEX idx_analysts_deleted         ON analysts (deleted);
CREATE INDEX idx_analysts_deleted_at      ON analysts (deleted_at);
CREATE INDEX idx_analysts_user_id         ON analysts (user_id);
CREATE INDEX idx_analysts_personal_info_id ON analysts (personal_info_id);